title: Dilip Katare
description: "A blog my tech journey"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dilip Katare
author-img: dilip4.jpg # add your photo
about-author: I am a Lead Developement Engineer at Nokia. This is the blogging space to share my experience. Views expressed here are solely my own.
social-twitter: dilipkatare # add your Twitter handle
social-github: dilipkatare  # add your Github handle
social-linkedin: dilip-katare-6113a121 # add your Linkedin handle
social-email:  # add your Email address

# Disqus
discus-identifier: #poonam_parhar

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
